import { renderMarkdown } from '../../utils/renderMarkdown.jsx';

export default function ExplanationDisplayBlock({ mode, explanation, onGenerate }) {
  const content = explanation?.[`${mode}Content`];
  const loading = explanation?.[`${mode}Loading`];
  const error = explanation?.[`${mode}Error`];

  if (loading) {
    return (
      <div className="explanation-display explanation-loading">
        <div className="shimmer-line" />
        <div className="shimmer-line width-85" />
        <div className="shimmer-line width-70" />
        <p>Generating explanation...</p>
      </div>
    );
  }

  if (error) {
    const serviceUnavailable = error.includes('npm run dev');
    return (
      <div className="explanation-display explanation-error">
        <p>{error}</p>
        {serviceUnavailable && <code>npm run dev</code>}
        <button type="button" onClick={onGenerate}>Try Again</button>
      </div>
    );
  }

  if (content) {
    return (
      <div className="explanation-display">
        <div className="explanation-prose">
          {renderMarkdown(content)}
        </div>
        <div className="explanation-actions">
          <button type="button" onClick={onGenerate}>{'\u21ba'} Regenerate</button>
          <span>{'\u2726'} Explanation generated by AI</span>
        </div>
      </div>
    );
  }

  return (
    <div className="explanation-display explanation-empty">
      Explanation will appear here after simulation completes.
    </div>
  );
}
